### ISSUE TITLE
Image presence error

### ISSUE THREAD

**Issue by itayariely** [AgeevAndrew/openxml_docx_templater#4]
Hi AgeevAndrew,

First I wanted to thank you for this GEM that is helping me very much in one of my projects.

I recently encountered a strange problem when I add an image in the area of the embedded code that breaks the XML.

Can you check the source of the problem?

The attached picture has a comparison of the files, and you can see that there is a deleted code section.

I also attach the files themselves.

Thanks
![screenshot from 2017-09-29 09-29-59](https://user-images.githubusercontent.com/3779412/31003654-7be9b99a-a4f9-11e7-9061-0972f8a51e7f.png)
[original file.docx](https://github.com/AgeevAndrew/openxml_docx_templater/files/1343303/original.file.docx)
[output file.docx](https://github.com/AgeevAndrew/openxml_docx_templater/files/1343304/output.file.docx)

Update:
*  this issue related to v 0.1.3 && v 0.2.0

**Comment by itayariely** [comment]
@AgeevAndrew @Kirillvs Do you have an idea of how to solve this?

**Comment by programyan** [comment]
Hello @itayariely 

Firstly, I would like to say: thank you for you report. Now we know, that this library is used not only us, and this is great!
This bug is related to rubyzip library, https://github.com/rubyzip/rubyzip#modify-docx-file-with-rubyzip 

We will solve this drawback as soon as possible. (I think in one or two weeks).

**Comment by itayariely** [comment]
Thanks for your attention and quick response @AgeevAndrew,
I just find way to solve it but not shore it is the best way.
you can see  [here](https://github.com/itayariely/openxml_docx_templater)
I change the embedded pattern from {% %} to {{% %}} and its worked!

**Comment by programyan** [comment]
Hello @itayariely 

I was wrong about this bug. It was just a disadvantage in my regexp pattern. So I fix it, and make a new version of this gem. Now your example works fine.

If you find any other bugs, please do not hesitate to contact us by opening new issue.
Thanks a lot.
